### ISSUE TITLE
Pretrained model with Imagenet dataset

### ISSUE THREAD

**Issue by MrXu** [titu1994/Wide-Residual-Networks#2]
It would be great if the pretrained model with imagenet dataset ca be provided. Wide residual network can be quite good at feature extracting. The pretrained model weight will help with transfer learning. :)

**Comment by titu1994** [comment]
@MrXu Having weights for ImageNet would be nice, but the problem is that I only have a single GPU on a laptop (980M) with less than 500 GB left on the HDD. 

My GPU with 4GB or RAM can't load the huge WRN-100-24 model (with a batch size of 4) and train on the 1.2 million images of ImageNet. Even if it could, it would take well over a month, maybe even more so I can't task it for that without burning out my GPU.

**Comment by titu1994** [comment]
Of course, if someone else trains a WRN model on ImageNet, please feel free to add a PR with the weights or add it to the releases (by mailing me or some other way)
